name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://dlcdnets.asus.com/pub/ASUS/ZenFone/ZS660KL/UL-ASUS_I001_1-ASUS-17.0240.2007.27-1.1.204-user.zip
  ROM_NAME: RogUI
  ZIP_NAME: RogUI
  TZ: Asia/Kolkata
  MIR: bit
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/qrovic/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo cp -r roms/9/RogUI roms/10
              sudo ./url2GSI.sh $ROM_URL $ROM_NAME

       - name: Print build info
         run: |
              ls ErfanGSIs/output
              cat ErfanGSIs/output/*-AB-*.txt
              ls ErfanGSIs/working
