name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://doc-14-5c-docs.googleusercontent.com/docs/securesc/oeg6ldbqfscnr0k8apdqsperdpt8rvqc/24qppdapp5ne8557qivfmtjn4bkjlnce/1596015300000/14484232756171817544/14256000017661765473/1sbyavTynhh8bC0IuhZyt52ROSUIOdsHe?e=download&authuser=0&nonce=v327sch5ssc3s&user=14256000017661765473&hash=ia0aqncdb2ip9ovhtmdas304m6ud2nf1
  ROM_NAME: ZUI
  ZIP_NAME: ZUI
  TZ: Asia/Kolkata
  MIR: bit
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/qrovic/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo cp -r roms/9/RogUI roms/10
              sudo ./url2GSI.sh $ROM_URL $ROM_NAME

       - name: Print build info
         run: |
              ls ErfanGSIs/output
              cat ErfanGSIs/output/*-AB-*.txt
              ls ErfanGSIs/working
